### ISSUE TITLE
anzu does not work well along with `multi-isearch-buffers`

### ISSUE THREAD

**Issue by pedrormjunior** [emacsorphanage/emacs-anzu#99]
When calling `multi-isearch-buffers`, anzu is automatically activated. The bug happens when the search goes to the 2nd+ specified buffers.

To reproduce the problem, here are the basic steps:

1. Call `multi-isearch-buffers`.
2. Specify at least two buffers to search on.
3. Search for a term that is present in the second or other buffer (not only in the first buffer).
4. Hit Return to stop the search when finding the term in a buffer other than the first one. Here, everything would be fine on that buffer.
5. Return to the first buffer (simply by `switch-to-buffer`, for example). Now you should notice that the anzu part on the mode-line is still active. Anything typed on that buffer is considered for the search. The search goes on not on that first buffer but on the other buffers selected for `multi-isearch-buffers` in step 2.

Another non-supportive characteristic in this scenario is that when searching from the second buffer on with `multi-isearch-buffers`, mode-line no longer indicates the anzu is activated (maybe it is not, in fact).

**Comment by syohex** [comment]
Sorry very late reply. This package is no longer maintained. If you want to add new feature, please fork repository and use it.

IMO: I never use `multi-isearch-buffers` and its support makes anzu.el complicated.
